# Generated by Django 4.1.7 on 2023-02-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_mymodel_campo3_alter_mymodel_campo4"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mymodel",
            old_name="campo1",
            new_name="field1",
        ),
        migrations.RenameField(
            model_name="mymodel",
            old_name="campo2",
            new_name="field2",
        ),
        migrations.RenameField(
            model_name="mymodel",
            old_name="campo3",
            new_name="field3",
        ),
        migrations.RenameField(
            model_name="mymodel",
            old_name="campo4",
            new_name="field4",
        ),
    ]
