# Generated by Django 4.1.7 on 2023-02-18 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_campo1_mymodel_field1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mymodel",
            old_name="field1",
            new_name="apostadores",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="field2",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="field3",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="field4",
        ),
        migrations.AddField(
            model_name="mymodel",
            name="hora_criacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="odd",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
