# Generated by Django 4.1.7 on 2023-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_user_alter_system_post_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mymodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo1", models.IntegerField()),
                ("campo2", models.CharField(max_length=10)),
                ("campo3", models.CharField(max_length=25)),
                ("campo4", models.CharField(max_length=6)),
            ],
        ),
    ]
