# Generated by Django 4.1.7 on 2023-04-01 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0007_rename_field1_mymodel_apostadores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system_post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_system_post",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
