# Generated by Django 4.1.7 on 2023-04-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_system_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system_post",
            name="user",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="System_Post",
        ),
    ]
